### ISSUE TITLE
walk需要支持break和continue, 急需支持

### ISSUE THREAD

**Issue by jianhuifan** [aligay/jsonuri#5]
比如： var data = { a: { aa: { aaa: ‘aaa’ }, isopen: true }, b: { bb: 'bb'} }
walk(data, function(obj, key, raw, path){
    if(obj.isopen==true){
        return true; //标示当前对象不再遍历, 类似 continue;
        return false: //总个跳出遍历，类似break
    }else{
    set(data, path.path+'data-path/', path.path);
    }
})
//  输出：  { a: { aa: { aaa: ‘aaa’ }, isopen: true }, b: { bb: 'bb’, data-path: ‘….’} , data-path: ‘…’}

**Comment by height** [comment]
done.
